export enum PageEndpoints {
  HOME = "/",
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  CALLBACK = "/callback",
  PROMOTION = "/promotion",
  PROMOTION_DETAIL = "/promotion/:id",
  PROMOTION_POST = "/promotion/post",
  VOTE = "/vote/:id",
  TEAM = "/team",
  CLUB = "/club/:id",
  VOTE_RESULT = "/vote/:id/result",
  MYPAGE = "/mypage",
  POST_TIME_SCHEDULE = "/post/time-schedule",
  MY_TIMETABLE_DETAIL = "/time-schedule/:id",
}

export enum ApiEndpotins {
  SIGN_IN = "/auth/login",
  SIGN_UP = "/auth/signup",
  REFRESH_TOKEN = "/auth/refresh",
  ME = "/users/me/info",
  CLUB = "/clubs",
  CLUB_DETAIL = "/clubs/:id",
  UNIVERSITIES = "/univ/all",
  CLUB_POLL = "/polls/clubs/:id",
  MY_TIMETABLE = "/users/me/timetables",
  MY_TIMETABLE_DETAIL = "/users/me/timetables/:id",
  POLL = "/polls/:id",
  POLL_RECOMMEND = "/polls/:id/songs",
}
